Fix refresh button and Settings Page
cs-22-sw-8-07/smartphone_app pull request #20
Opened 2022-04-17 17:37 UTC by Determinatoro

2022-04-18 09:04 UTC, LivHolm reviewed
Alle test kørte, ingen gav fejl, og det hele ser godt ud. Jeg har bare den ene kommentar.

2022-04-18 09:04 UTC, LivHolm commented on lib/pages/main/main_page_bloc.dart
> +          await _startRecommendation();
Jeg kan ikke huske det helt præcis, men var der tale om at tjekke for en null værdi her? Hvis det ikke længere er relevant så ignorer den her kommentar

2022-04-19 07:38 UTC, LivHolm approved these changes

2022-04-19 08:43 UTC, ProgDaniel requested changes
PixelRender fejl i Playlist Builder

════════ Exception caught by widgets library ═══════════════════════════════════
BoxConstraints has a negative minimum height.

main_page_ui, line 348 - 358

2022-04-19 09:28 UTC, ProgDaniel approved these changes

2022-04-19 09:37 UTC, closed without merging